/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { InvitationService } from "../invitation.service";
import { InvitationCreateInput } from "./InvitationCreateInput";
import { Invitation } from "./Invitation";
import { InvitationFindManyArgs } from "./InvitationFindManyArgs";
import { InvitationWhereUniqueInput } from "./InvitationWhereUniqueInput";
import { InvitationUpdateInput } from "./InvitationUpdateInput";

export class InvitationControllerBase {
  constructor(protected readonly service: InvitationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Invitation })
  async createInvitation(
    @common.Body() data: InvitationCreateInput
  ): Promise<Invitation> {
    return await this.service.createInvitation({
      data: data,
      select: {
        createdAt: true,
        emailOrPhone: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Invitation] })
  @ApiNestedQuery(InvitationFindManyArgs)
  async invitations(@common.Req() request: Request): Promise<Invitation[]> {
    const args = plainToClass(InvitationFindManyArgs, request.query);
    return this.service.invitations({
      ...args,
      select: {
        createdAt: true,
        emailOrPhone: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Invitation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async invitation(
    @common.Param() params: InvitationWhereUniqueInput
  ): Promise<Invitation | null> {
    const result = await this.service.invitation({
      where: params,
      select: {
        createdAt: true,
        emailOrPhone: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Invitation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateInvitation(
    @common.Param() params: InvitationWhereUniqueInput,
    @common.Body() data: InvitationUpdateInput
  ): Promise<Invitation | null> {
    try {
      return await this.service.updateInvitation({
        where: params,
        data: data,
        select: {
          createdAt: true,
          emailOrPhone: true,
          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Invitation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteInvitation(
    @common.Param() params: InvitationWhereUniqueInput
  ): Promise<Invitation | null> {
    try {
      return await this.service.deleteInvitation({
        where: params,
        select: {
          createdAt: true,
          emailOrPhone: true,
          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
